# Generated by Django 4.0.1 on 2022-02-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopcat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('photos', models.ImageField(upload_to='images')),
            ],
        ),
    ]
