# Generated by Django 4.0.2 on 2022-02-14 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryshop', '0003_item_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
    ]
